/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Util.TeladeFundo;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author eduar
 */
public class main extends javax.swing.JFrame {

    TeladeFundo tela;
    TelaCliente telacliente;
    TelaFuncionario telafuncionario;
    TelaEntregador telaentregador;
    TelaCardapio telacardapio;
    TelaPedido telapedido;
    TelaProducao telaproducao;
    
    
    public main() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setLayout(new GridLayout());
        tela = new TeladeFundo("/Imagens/acaiacademico.jpeg");
        getContentPane().add(tela);
        
        menu_clientes.setIcon(new ImageIcon(getClass().getResource("/Imagens/cliente.png")));
        menu_funcionarios.setIcon(new ImageIcon(getClass().getResource("/Imagens/funcionario.png")));
        menu_cardapio.setIcon(new ImageIcon(getClass().getResource("/Imagens/cardapio.png")));
        menu_entregador.setIcon(new ImageIcon(getClass().getResource("/Imagens/entregador.png")));
        
        menu_cadastro.setIcon(new ImageIcon(getClass().getResource("/Imagens/cadastrar.png")));
        menu_financeiro.setIcon(new ImageIcon(getClass().getResource("/Imagens/dinheiro.png")));
        menu_relatorio.setIcon(new ImageIcon(getClass().getResource("/Imagens/relatorio.png")));
        menu_sair.setIcon(new ImageIcon(getClass().getResource("/Imagens/sair.png")));
        
        menu_pedido.setIcon(new ImageIcon(getClass().getResource("/Imagens/pedido.png")));
        
        menu_tela_producao.setIcon(new ImageIcon(getClass().getResource("/Imagens/producao.png")));
        menu_producao.setIcon(new ImageIcon(getClass().getResource("/Imagens/cozinha.png")));
        
        ImageIcon icone = new ImageIcon (getClass().getResource("/Imagens/icon_acaiacademico.png"));
        setIconImage(icone.getImage());
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        menu_clientes = new javax.swing.JMenuItem();
        menu_funcionarios = new javax.swing.JMenuItem();
        menu_cardapio = new javax.swing.JMenuItem();
        menu_entregador = new javax.swing.JMenuItem();
        menu_financeiro = new javax.swing.JMenu();
        menu_pedido = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        menu_producao = new javax.swing.JMenu();
        menu_tela_producao = new javax.swing.JMenuItem();
        menu_sair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Açaí Acadêmico");

        menu_cadastro.setText("Cadastro");
        menu_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_clientes.setText("Clientes");
        menu_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clientesActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_clientes);

        menu_funcionarios.setText("Funcionários");
        menu_funcionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_funcionariosActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_funcionarios);

        menu_cardapio.setText("Cardápio");
        menu_cardapio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cardapioActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_cardapio);

        menu_entregador.setText("Entregador");
        menu_entregador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_entregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_entregadorActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_entregador);

        jMenuBar1.add(menu_cadastro);

        menu_financeiro.setText("Financeiro");
        menu_financeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_pedido.setText("Pedido");
        menu_pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pedidoActionPerformed(evt);
            }
        });
        menu_financeiro.add(menu_pedido);

        jMenuBar1.add(menu_financeiro);

        menu_relatorio.setText("Relatório");
        menu_relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(menu_relatorio);

        menu_producao.setText("Produção");
        menu_producao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_tela_producao.setText("Tela");
        menu_tela_producao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_tela_producao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tela_producaoActionPerformed(evt);
            }
        });
        menu_producao.add(menu_tela_producao);

        jMenuBar1.add(menu_producao);

        menu_sair.setText("Sair");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("Sair");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_sair.add(jMenuItem1);

        jMenuBar1.add(menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clientesActionPerformed

        telacliente = new TelaCliente();
        tela.add(telacliente);
        telacliente.setVisible(true);
    }//GEN-LAST:event_menu_clientesActionPerformed

    private void menu_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_funcionariosActionPerformed
        telafuncionario = new TelaFuncionario();
        tela.add(telafuncionario);
        telafuncionario.setVisible(true);
    }//GEN-LAST:event_menu_funcionariosActionPerformed

    private void menu_entregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_entregadorActionPerformed
        telaentregador = new TelaEntregador();
        tela.add( telaentregador);
        telaentregador.setVisible(true);
    }//GEN-LAST:event_menu_entregadorActionPerformed

    private void menu_cardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cardapioActionPerformed
       telacardapio = new TelaCardapio();
       tela.add(telacardapio);
       telacardapio.setVisible(true);
    }//GEN-LAST:event_menu_cardapioActionPerformed

    private void menu_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pedidoActionPerformed
       telapedido = new TelaPedido(1);
       tela.add(telapedido);
       telapedido.setVisible(true);
    }//GEN-LAST:event_menu_pedidoActionPerformed

    private void menu_tela_producaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tela_producaoActionPerformed
        telaproducao = new TelaProducao();
        
        telaproducao.setVisible(true);
    }//GEN-LAST:event_menu_tela_producaoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenuItem menu_cardapio;
    private javax.swing.JMenuItem menu_clientes;
    private javax.swing.JMenuItem menu_entregador;
    private javax.swing.JMenu menu_financeiro;
    private javax.swing.JMenuItem menu_funcionarios;
    private javax.swing.JMenuItem menu_pedido;
    private javax.swing.JMenu menu_producao;
    private javax.swing.JMenu menu_relatorio;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenuItem menu_tela_producao;
    // End of variables declaration//GEN-END:variables
}
